/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as SnippetsEditorRouteImport } from './routes/snippets.editor'
import { Route as SettingsStorageRouteImport } from './routes/settings/storage'
import { Route as SettingsIntegrationsRouteImport } from './routes/settings/integrations'
import { Route as ProjectProjectIdRouteImport } from './routes/project/$projectId'
import { Route as DocsLayoutSnappingRouteImport } from './routes/docs/layout-snapping'
import { Route as ProjectProjectIdIndexRouteImport } from './routes/project/$projectId/index'
import { Route as ProjectProjectIdSlideSlideIdRouteImport } from './routes/project/$projectId/slide/$slideId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const SnippetsEditorRoute = SnippetsEditorRouteImport.update({
  id: '/snippets/editor',
  path: '/snippets/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsStorageRoute = SettingsStorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsIntegrationsRoute = SettingsIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => SettingsRoute,
} as any)
const ProjectProjectIdRoute = ProjectProjectIdRouteImport.update({
  id: '/project/$projectId',
  path: '/project/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsLayoutSnappingRoute = DocsLayoutSnappingRouteImport.update({
  id: '/layout-snapping',
  path: '/layout-snapping',
  getParentRoute: () => DocsRoute,
} as any)
const ProjectProjectIdIndexRoute = ProjectProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectProjectIdRoute,
} as any)
const ProjectProjectIdSlideSlideIdRoute =
  ProjectProjectIdSlideSlideIdRouteImport.update({
    id: '/slide/$slideId',
    path: '/slide/$slideId',
    getParentRoute: () => ProjectProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/library': typeof LibraryRoute
  '/settings': typeof SettingsRouteWithChildren
  '/docs/layout-snapping': typeof DocsLayoutSnappingRoute
  '/project/$projectId': typeof ProjectProjectIdRouteWithChildren
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/storage': typeof SettingsStorageRoute
  '/snippets/editor': typeof SnippetsEditorRoute
  '/docs/': typeof DocsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/project/$projectId/': typeof ProjectProjectIdIndexRoute
  '/project/$projectId/slide/$slideId': typeof ProjectProjectIdSlideSlideIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/docs/layout-snapping': typeof DocsLayoutSnappingRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/storage': typeof SettingsStorageRoute
  '/snippets/editor': typeof SnippetsEditorRoute
  '/docs': typeof DocsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/project/$projectId': typeof ProjectProjectIdIndexRoute
  '/project/$projectId/slide/$slideId': typeof ProjectProjectIdSlideSlideIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/library': typeof LibraryRoute
  '/settings': typeof SettingsRouteWithChildren
  '/docs/layout-snapping': typeof DocsLayoutSnappingRoute
  '/project/$projectId': typeof ProjectProjectIdRouteWithChildren
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/storage': typeof SettingsStorageRoute
  '/snippets/editor': typeof SnippetsEditorRoute
  '/docs/': typeof DocsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/project/$projectId/': typeof ProjectProjectIdIndexRoute
  '/project/$projectId/slide/$slideId': typeof ProjectProjectIdSlideSlideIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/library'
    | '/settings'
    | '/docs/layout-snapping'
    | '/project/$projectId'
    | '/settings/integrations'
    | '/settings/storage'
    | '/snippets/editor'
    | '/docs/'
    | '/settings/'
    | '/project/$projectId/'
    | '/project/$projectId/slide/$slideId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/library'
    | '/docs/layout-snapping'
    | '/settings/integrations'
    | '/settings/storage'
    | '/snippets/editor'
    | '/docs'
    | '/settings'
    | '/project/$projectId'
    | '/project/$projectId/slide/$slideId'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/library'
    | '/settings'
    | '/docs/layout-snapping'
    | '/project/$projectId'
    | '/settings/integrations'
    | '/settings/storage'
    | '/snippets/editor'
    | '/docs/'
    | '/settings/'
    | '/project/$projectId/'
    | '/project/$projectId/slide/$slideId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRouteWithChildren
  LibraryRoute: typeof LibraryRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  ProjectProjectIdRoute: typeof ProjectProjectIdRouteWithChildren
  SnippetsEditorRoute: typeof SnippetsEditorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/snippets/editor': {
      id: '/snippets/editor'
      path: '/snippets/editor'
      fullPath: '/snippets/editor'
      preLoaderRoute: typeof SnippetsEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/storage': {
      id: '/settings/storage'
      path: '/storage'
      fullPath: '/settings/storage'
      preLoaderRoute: typeof SettingsStorageRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/integrations': {
      id: '/settings/integrations'
      path: '/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof SettingsIntegrationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/project/$projectId': {
      id: '/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/project/$projectId'
      preLoaderRoute: typeof ProjectProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/layout-snapping': {
      id: '/docs/layout-snapping'
      path: '/layout-snapping'
      fullPath: '/docs/layout-snapping'
      preLoaderRoute: typeof DocsLayoutSnappingRouteImport
      parentRoute: typeof DocsRoute
    }
    '/project/$projectId/': {
      id: '/project/$projectId/'
      path: '/'
      fullPath: '/project/$projectId/'
      preLoaderRoute: typeof ProjectProjectIdIndexRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/slide/$slideId': {
      id: '/project/$projectId/slide/$slideId'
      path: '/slide/$slideId'
      fullPath: '/project/$projectId/slide/$slideId'
      preLoaderRoute: typeof ProjectProjectIdSlideSlideIdRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
  }
}

interface DocsRouteChildren {
  DocsLayoutSnappingRoute: typeof DocsLayoutSnappingRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsLayoutSnappingRoute: DocsLayoutSnappingRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

interface SettingsRouteChildren {
  SettingsIntegrationsRoute: typeof SettingsIntegrationsRoute
  SettingsStorageRoute: typeof SettingsStorageRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsIntegrationsRoute: SettingsIntegrationsRoute,
  SettingsStorageRoute: SettingsStorageRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface ProjectProjectIdRouteChildren {
  ProjectProjectIdIndexRoute: typeof ProjectProjectIdIndexRoute
  ProjectProjectIdSlideSlideIdRoute: typeof ProjectProjectIdSlideSlideIdRoute
}

const ProjectProjectIdRouteChildren: ProjectProjectIdRouteChildren = {
  ProjectProjectIdIndexRoute: ProjectProjectIdIndexRoute,
  ProjectProjectIdSlideSlideIdRoute: ProjectProjectIdSlideSlideIdRoute,
}

const ProjectProjectIdRouteWithChildren =
  ProjectProjectIdRoute._addFileChildren(ProjectProjectIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRouteWithChildren,
  LibraryRoute: LibraryRoute,
  SettingsRoute: SettingsRouteWithChildren,
  ProjectProjectIdRoute: ProjectProjectIdRouteWithChildren,
  SnippetsEditorRoute: SnippetsEditorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
