/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SnippetsNewRouteImport } from './routes/snippets.new'
import { Route as SettingsStorageRouteImport } from './routes/settings/storage'
import { Route as SettingsIntegrationsRouteImport } from './routes/settings/integrations'
import { Route as ProjectProjectIdRouteImport } from './routes/project/$projectId'
import { Route as ProjectProjectIdIndexRouteImport } from './routes/project/$projectId/index'
import { Route as ProjectProjectIdSlideSlideIdRouteImport } from './routes/project/$projectId/slide/$slideId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SnippetsNewRoute = SnippetsNewRouteImport.update({
  id: '/snippets/new',
  path: '/snippets/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsStorageRoute = SettingsStorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsIntegrationsRoute = SettingsIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => SettingsRoute,
} as any)
const ProjectProjectIdRoute = ProjectProjectIdRouteImport.update({
  id: '/project/$projectId',
  path: '/project/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdIndexRoute = ProjectProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectProjectIdRoute,
} as any)
const ProjectProjectIdSlideSlideIdRoute =
  ProjectProjectIdSlideSlideIdRouteImport.update({
    id: '/slide/$slideId',
    path: '/slide/$slideId',
    getParentRoute: () => ProjectProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/settings': typeof SettingsRouteWithChildren
  '/project/$projectId': typeof ProjectProjectIdRouteWithChildren
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/storage': typeof SettingsStorageRoute
  '/snippets/new': typeof SnippetsNewRoute
  '/settings/': typeof SettingsIndexRoute
  '/project/$projectId/': typeof ProjectProjectIdIndexRoute
  '/project/$projectId/slide/$slideId': typeof ProjectProjectIdSlideSlideIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/storage': typeof SettingsStorageRoute
  '/snippets/new': typeof SnippetsNewRoute
  '/settings': typeof SettingsIndexRoute
  '/project/$projectId': typeof ProjectProjectIdIndexRoute
  '/project/$projectId/slide/$slideId': typeof ProjectProjectIdSlideSlideIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/settings': typeof SettingsRouteWithChildren
  '/project/$projectId': typeof ProjectProjectIdRouteWithChildren
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/storage': typeof SettingsStorageRoute
  '/snippets/new': typeof SnippetsNewRoute
  '/settings/': typeof SettingsIndexRoute
  '/project/$projectId/': typeof ProjectProjectIdIndexRoute
  '/project/$projectId/slide/$slideId': typeof ProjectProjectIdSlideSlideIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/library'
    | '/settings'
    | '/project/$projectId'
    | '/settings/integrations'
    | '/settings/storage'
    | '/snippets/new'
    | '/settings/'
    | '/project/$projectId/'
    | '/project/$projectId/slide/$slideId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/library'
    | '/settings/integrations'
    | '/settings/storage'
    | '/snippets/new'
    | '/settings'
    | '/project/$projectId'
    | '/project/$projectId/slide/$slideId'
  id:
    | '__root__'
    | '/'
    | '/library'
    | '/settings'
    | '/project/$projectId'
    | '/settings/integrations'
    | '/settings/storage'
    | '/snippets/new'
    | '/settings/'
    | '/project/$projectId/'
    | '/project/$projectId/slide/$slideId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LibraryRoute: typeof LibraryRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  ProjectProjectIdRoute: typeof ProjectProjectIdRouteWithChildren
  SnippetsNewRoute: typeof SnippetsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/snippets/new': {
      id: '/snippets/new'
      path: '/snippets/new'
      fullPath: '/snippets/new'
      preLoaderRoute: typeof SnippetsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/storage': {
      id: '/settings/storage'
      path: '/storage'
      fullPath: '/settings/storage'
      preLoaderRoute: typeof SettingsStorageRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/integrations': {
      id: '/settings/integrations'
      path: '/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof SettingsIntegrationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/project/$projectId': {
      id: '/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/project/$projectId'
      preLoaderRoute: typeof ProjectProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId/': {
      id: '/project/$projectId/'
      path: '/'
      fullPath: '/project/$projectId/'
      preLoaderRoute: typeof ProjectProjectIdIndexRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/slide/$slideId': {
      id: '/project/$projectId/slide/$slideId'
      path: '/slide/$slideId'
      fullPath: '/project/$projectId/slide/$slideId'
      preLoaderRoute: typeof ProjectProjectIdSlideSlideIdRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
  }
}

interface SettingsRouteChildren {
  SettingsIntegrationsRoute: typeof SettingsIntegrationsRoute
  SettingsStorageRoute: typeof SettingsStorageRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsIntegrationsRoute: SettingsIntegrationsRoute,
  SettingsStorageRoute: SettingsStorageRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface ProjectProjectIdRouteChildren {
  ProjectProjectIdIndexRoute: typeof ProjectProjectIdIndexRoute
  ProjectProjectIdSlideSlideIdRoute: typeof ProjectProjectIdSlideSlideIdRoute
}

const ProjectProjectIdRouteChildren: ProjectProjectIdRouteChildren = {
  ProjectProjectIdIndexRoute: ProjectProjectIdIndexRoute,
  ProjectProjectIdSlideSlideIdRoute: ProjectProjectIdSlideSlideIdRoute,
}

const ProjectProjectIdRouteWithChildren =
  ProjectProjectIdRoute._addFileChildren(ProjectProjectIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LibraryRoute: LibraryRoute,
  SettingsRoute: SettingsRouteWithChildren,
  ProjectProjectIdRoute: ProjectProjectIdRouteWithChildren,
  SnippetsNewRoute: SnippetsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
